### PR TITLE
Protocol 3.5 implementation

### PR DESCRIPTION
**Pull request by Brechtpd**

### CODE REVIEW

**Review by yueawang — DISMISSED** [review]
Hi, @Brechtpd, generally this PR looks good to me.
I have 1 question about conditional transfer. Circuit code shows that conditional transfer does not rely on the user's signature, I just wonder how do we verify the transfer(or say the condition) is valid? I did not join the feature discussion before, so I might miss some crucial ideas.

**Comment by Brechtpd** [comment]
If `type > 0` (which needs to be the case when no signature is provided in the circuit) then we check onchain if the transfer was approved by the user. So in practice, if `type == 1` we make use of the DA data (which contains token, from, to, amount) and see if this particular transfer was approved some other way.

**Comment by yueawang** [comment]
> So in practice, if `type == 1` we make use of the DA data (which contains token, from, to, amount) and see if this particular transfer was approved some other way.

Does that mean only our contract check the approval and then circuit just verify the execution result, i.e., the balance? DA includes token/from/to/amount only seems can be easily forged I think, will that be a problem?

**Comment by Brechtpd** [comment]
> Does that mean only our contract check the approval and then circuit just verify the execution result, i.e., the balance? 

Yes, the actual transfer is done just like before by creating a dummy transfer request, but without a valid signature. So everything except the signature checking is completely the same with other transfers. So instead of approving of the transfer offchain with an EdDSA signature the transfer is approved onchain by calling `approveOffchainTransfer`.

> DA includes token/from/to/amount only seems can be easily forged I think, will that be a problem?

All DA data onchain is hashed used as input in the circuit. It needs to match the DA data as produced by the circuit, so it cannot be forged because the DA is the result of the transfer. It needs to match exactly with what happened in the circuit.

**Comment by yueawang** [comment]
Thanks @Brechtpd. I was trying to understand this as the on-chain deposit but failed to find a solid link between the request and the circuit, I will read the related contract code you mentioned and get back to you if I have more questions.

**Review by yueawang — APPROVED** [review]

**Pull request merged**
